### ISSUE TITLE
ERROR Unable to create file /Users/kylefalconer/git/BLiC-Java/logs/debug.log

### ISSUE THREAD

**Issue by evankroske** [codeforsanjose/BLiC-Java#7]
Looks like src/main/resources/log4j2.xml is the problem. Let's just use java.util.logging.Logger and allow it to send logs to STDERR, which it does by default. This will also remove some dependencies.

**Comment by Kyle-Falconer** [comment]
The intention behind including log4j was to have robust logging support. I wanted the program's output to go to stdout, but I also wanted debug information that wouldn't be suited for stderr, so I'm using log4j to write logging information to a log file. It also allows for selecting the log level for debugging/performance balance.

**Comment by Kyle-Falconer** [comment]
I'm open to discussing replacing log4j with java.util.logging.Logger, but my initial impression with log4j is it's a more robust solution for the long-term.

**Comment by evankroske** [comment]
Right now, the tool throws the error in the title of this issue when it's run. We can stick with log4j, but I think we should fix the error.

**Comment by evankroske** [comment]
It works now. I still think that you should write the progress logs to STDERR so that I can see the program working.
