### ISSUE TITLE
Race condition in pages.put(u, w)

### ISSUE THREAD

**Issue by ethanp** [codeforsanjose/BLiC-Java#9]
A URL could be added to the `pages` map between the time [`!this.pages.containsKey(u)`](https://github.com/codeforsanjose/BLiC-Java/blob/master/src/main/java/com/codeforsanjose/blic/Crawler.java#L69) runs, and the time [`this.pages.put(u,w)`](https://github.com/codeforsanjose/BLiC-Java/blob/master/src/main/java/com/codeforsanjose/blic/Crawler.java#L73) runs. This means another Crawler could be running for a `WebPage` that will be replaced from the `pages` map, updating a data structure that won't be printed in the report, and that work will be duplicated later.

This could be fixed by using `ConcurrentHashMap#putIfAbsent(absUrl, webPage)` instead of `put`. This would make `filterUnseen` only necessary for resolving absolute URLs.

**Comment by Kyle-Falconer** [comment]
Nice find. You could fix it if you want :)

**Comment by ethanp** [comment]
Ok I will submit a PR

**Comment by Kyle-Falconer** [comment]
@ethanp I've actually invited you to this C4SJ team, so then you can just work directly on this repo, make a branch, commit, and we can merge it in.
